// config.js — Configuración del negocio (multi-tenant)
// El tenant se resuelve desde ?local= en la URL o desde el dominio.

(function () {
  const _domainMap = {
    'gitananails.synaptechspa.cl':        'gitana',
    'barberiaelegance.synaptechspa.cl':   'elegance',
    'barberiaferraza.synaptechspa.cl':    'ferraza',
    'mapubarbershop.synaptechspa.cl':     'mapubarbershop',
    'chameleonbarber.synaptechspa.cl':    'chameleon',
    'deluxeperfumes.synaptechspa.cl':     'deluxeperfumes',
    'barberiadjones.synaptechspa.cl':     'lumen',
    'delnerobarber.synaptechspa.cl':      'delnero',
    'marcelohairdressing.synaptechspa.cl': 'marcelo_hairdressing',
    'marcelo-hairdressing.synaptechspa.cl': 'marcelo_hairdressing',
    'marcelopalma.synaptechspa.cl':       'marcelo_hairdressing',
    'aurasalon.synaptechspa.cl':          'aura',
    'aurasalonmalegrooming.synaptech.cl': 'aura',
    'aurasalonmalegrooming.synaptechspa.cl': 'aura',
    'machos.synaptechspa.cl':             'machos',
    'infinity.synaptechspa.cl':           'infinity',
    'sionbarberia.synaptechspa.cl':       'sionbarberia',
    'barberiasion.synaptechspa.cl':       'sionbarberia',
  };

  const _tenants = {
    elegance: {
      categoriasServicio: ['Cortes', 'Barba', 'Combos', 'Extras', 'Otro'],
      nombre:          '𝐄𝐥𝐞𝐠𝐚𝐧𝐜𝐞 𝐛𝐚𝐫𝐛𝐞𝐫𝐬𝐡𝐨𝐩',
      nombreCorto:     'Elegance',
      slogan:          'No es un corte, es elegancia que te mereces',
      logo:            '/logo.jpg',
      direccion:       '📍 Ecuador 243 | Viña del Mar',
      horario:         '🕒 Lunes-Sáb: 10-20h | Dom: 12-20h. ¡Reserva ya!',
      telefono:        '',
      club:            'Club Elegance',
      instagram:       'https://www.instagram.com/elegance.cl_/',
      instagramHandle: '@elegance.cl_',
      waEmoji:         '✂️',
      googleReviewUrl: '',
      ratingGeneral: 0,
      totalReviews:  0,
      reviews:       [],
      barberos: [
        { nombre: 'Nicolas Fabian', foto: 'Fabian.png', disponible: true },
      ],
    },
    ferraza: {
      categoriasServicio: ['Cortes', 'Barba', 'Combos', 'Extras', 'Otro'],
      nombre:          'Barbería Ferraza',
      nombreCorto:     'Ferraza',
      pageTitle:       'Barbería Ferraza | El cambio comienza por ti',
      bodyBg:          '#000000',
      slogan:          'El cambio comienza por ti',
      logo:            '/local1.jpg',
      direccion:       '📍 Av. Libertad 63 / Local 28',
      horario:         '🕒 Lun a Sáb: 10:00 – 20:00 hrs.',
      telefono:        '56994269228',
      club:            'Club Ferraza',
      instagram:       '',
      instagramHandle: '',
      waEmoji:         '✂️',
      googleReviewUrl: 'https://g.page/r/CT_OVpP50fd8EBM/review',
      ratingGeneral: 4.8,
      totalReviews:  46,
      reviews: [
        { author: 'Iván Klemencic',      rating: 5, text: 'Excelente atención. Quien atiende demuestra profesionalismo en lo que hace, lo recomiendo totalmente. Además, está la posibilidad de agendar para el mismo día.' },
        { author: 'Juan P. Mesa',         rating: 5, text: 'Primero que todo, excelente servicio. Un lugar muy grato, limpio y muy buena disposición de Nicolás. Me atendieron al tiro, excelente corte de cabello, todo bien. Recomendable 100%.' },
        { author: 'Nicolas Pardo',        rating: 5, text: 'Excelente servicio por parte de Nico, lugar con un muy buen ambiente y atención. Para relajarse un rato. Recomendado!' },
      ],
      barberos: [
        { nombre: 'Nicolas Fabian', foto: 'Fabian.png', disponible: true },
      ],
    },
    gitana: {
      categoriasServicio: ['Uñas', 'Pestañas', 'Cejas', 'Combos', 'Otro'],
      nombre:          'Gitana Nails Studio',
      nombreCorto:     'Gitana',
      slogan:          'Estudio de Uñas y Pestañas',
      logo:            '/gitana.png',
      direccion:       '📍 Las Encinas 1390 local 18 | Concón',
      horario:         'Estudio de uñas y pestañas en Concón | Atención con hora previa',
      telefono:        '56997023355',
      club:            'Club Gitana',
      instagram:       'https://www.instagram.com/gitana.nails.studio',
      instagramHandle: '@gitana.nails.studio',
      waEmoji:         '💅',
      googleReviewUrl: '',
      ratingGeneral: 0,
      totalReviews:  0,
      reviews:       [],
      barberos: [
        { nombre: 'Sabina', foto: null, disponible: true },
        { nombre: 'Clau',   foto: null, disponible: true },
        { nombre: 'Cony',   foto: null, disponible: true },
        { nombre: 'Gigi',   foto: null, disponible: true },
      ],
    },
    chameleon: {
      categoriasServicio: ['Ritual del Cabello', 'Ritual de la Barba', 'Diseño de Cejas', 'Otros'],
      nombre:          'Chameleon Barber Studio',
      nombreCorto:     'Chameleon',
      pageTitle:       'Chameleon Barber Studio | Agenda tu hora',
      slogan:          'Clásico y moderno, perfecto para tí!',
      logo:            '/local3.jpg',
      direccion:       '📍 Av. Libertad 868 | Viña del Mar',
      horario:         '🕒 Lun a Sáb: 10:30 – 20:00 hrs.',
      telefono:        '56928186861',
      club:            'Club Chameleon',
      instagram:       'https://www.instagram.com/chameleon.barberstudio/',
      instagramHandle: '@chameleon.barberstudio',
      waEmoji:         '✂️',
      ratingGeneral: 5.0,
      totalReviews:  226,
      reviews: [
        { author: 'Carlos Andrés Yáñez', rating: 5, text: 'Excelente servicio! Vengo de Santiago y confié en esta barbería para cortarme el pelo más barba, el barbero supo cortarme tal cual lo solicitado. Muy profesional!' },
        { author: 'Cristian Veas',        rating: 5, text: 'Profesionales del corte de pelo y barba. Amables y buena onda, con tema de conversación, ambiente muy agradable y precio acorde al resultado. 5/5' },
        { author: 'Jorge Miranda',         rating: 5, text: 'Me atendí con Omar, un crack, muy amable y gentil al usar las tijeras, creo que es lo que más destacaría, primera vez que voy, y volvería a ir.' },
      ],
      googleReviewUrl: 'https://g.page/r/CQJzgHEVI1p-EBM/review',
      features: {
        hasCourses: true,
        courses: {
          title:       'Cursos de Barbería',
          description: 'Aprende con los mejores. Formamos a los próximos profesionales del arte de la barbería con técnicas clásicas y modernas, desde cero hasta nivel avanzado.',
          ctaMsg:      'Hola Chameleon! Quiero información sobre los cursos de barbería 🎓',
        },
        hasChairRental: true,
        chairRental: {
          title:       'Arriendo de Sillones',
          description: 'Únete a nuestro equipo. Alquila tu espacio en nuestro studio y trabaja con total autonomía en un ambiente profesional y bien equipado.',
          ctaMsg:      'Hola Chameleon! Me interesa el arriendo de un sillón en el studio ✂️',
        },
      },
      barberos: [
        { nombre: 'Omar Peñafiel',  foto: null, disponible: true },
        { nombre: 'Juan Vásquez',   foto: null, disponible: true },
        { nombre: 'David Figueredo',foto: null, disponible: true },
      ],
    },
    lumen: {
      categoriasServicio: ['Cortes', 'Barba', 'Combos', 'Extras', 'Otros'],
      nombre:          "D'Jones Barber",
      nombreCorto:     "D'Jones",
      pageTitle:       "D'Jones Barber | Estilo y tradición",
      slogan:          'Estilo y tradición',
      logo:            '/djones.png',
      direccion:       '📍 Villanelo 279 | Viña del Mar',
      horario:         '🕒 Lun a Sáb: 10:00 – 20:15 hrs | Dom: 09:00 – 20:00 hrs',
      telefono:        '56929808223',
      club:            "Club D'Jones",
      instagram:       'https://www.instagram.com/d.jonesbarberia/',
      instagramHandle: '@d.jonesbarberia',
      waEmoji:         '⚓',
      googleReviewUrl: '',
      ratingGeneral: 4.98,
      totalReviews:  64,
      reviews: [
        { author: 'Pablo', rating: 5, text: 'Excelente como siempre buen ambiente ' },
        { author: 'Abel', rating: 5, text: 'Siempre cuando voy és un excelente servicio. Recomendado totalmente. Excelentes trabajadores' },
      ],
      barberos: [
        { nombre: 'Brayan Soto', foto: 'https://dcx13p9dsx90t.cloudfront.net/uploads/attachment_images/250141/attachment_870cf32e763eb130.png', disponible: true },
        { nombre: 'Valeria Narvaez', foto: 'https://dcx13p9dsx90t.cloudfront.net/uploads/attachment_images/278445/attachment_c1a02d21144da9f9.png', disponible: true },
        { nombre: 'Jorge Espinosa', foto: null, disponible: true },
      ],
    },
    deluxeperfumes: {
      categoriasServicio: ['Perfumes', 'Sets', 'Miniaturas', 'Accesorios', 'Otro'],
      nombre:          'Deluxe Perfumes',
      nombreCorto:     'Deluxe',
      pageTitle:       'Deluxe Perfumes | Tu fragancia perfecta',
      slogan:          'Tu fragancia perfecta',
      logo:            '/logo5.jpg',
      logo2:           '/logo5.jpg',
      direccion:       '📍 1/2 Oriente 831, Oficina 601, Viña del Mar',
      horario:         '🚚 Delivery en Viña, Valparaíso y Con-Con.',
      telefono:        '',
      club:            'Club Deluxe',
      instagram:       '',
      instagramHandle: '',
      waEmoji:         '🌸',
      googleReviewUrl: '',
      ratingGeneral: 0,
      totalReviews:  0,
      reviews:       [],
      barberos:        [],
    },
    delnero: {
      categoriasServicio: ['Cortes', 'Barba', 'Combos', 'Extras', 'Otro'],
      nombre:          'Del Nero Barber',
      nombreCorto:     'Del Nero',
      pageTitle:       'Del Nero Barber | Agenda tu hora',
      slogan:          'Estilo que define. Arte que trasciende.',
      logo:            '/nero.jpg',
      direccion:       '📍 Curauma / Placilla',
      horario:         '🕒 Lun a Sáb: 10:00 – 20:00 hrs.',
      telefono:        '',
      club:            'Club Del Nero',
      instagram:       '',
      instagramHandle: '',
      waEmoji:         '✂️',
      googleReviewUrl: 'https://g.page/r/CZ39qJYmBtlqEBM/review',
      ratingGeneral: 0,
      totalReviews:  0,
      reviews:       [],
      barberos: [],
    },
    marcelo_hairdressing: {
      categoriasServicio: ['Cortes', 'Barba', 'Combos', 'Extras', 'Otro'],
      nombre:          'Marcelo Palma',
      nombreCorto:     'Marcelo',
      pageTitle:       'Marcelo Palma | Agenda tu hora',
      slogan:          'Hairdressing & Estilo',
      logo:            '/marcelo1.png',
      direccion:       '📍 Curauma / Placilla',
      horario:         '🕒 Lun a Sáb: 10:00 – 20:00 hrs.',
      telefono:        '',
      club:            'Club Marcelo',
      instagram:       '',
      instagramHandle: '',
      waEmoji:         '✂️',
      googleReviewUrl: '',
      ratingGeneral: 0,
      totalReviews:  0,
      reviews:       [],
      barberos: [],
    },
    mapubarbershop: {
      categoriasServicio: ['Cortes', 'Barba', 'Combos', 'Extras', 'Otro'],
      nombre:          'Mapu Barber Shop',
      nombreCorto:     'Mapu',
      pageTitle:       'Mapu Barber Shop | Vive la Experiencia',
      slogan:          'Vive la Experiencia',
      sobreNosotros:   'Fundada en 2017 en Valparaíso, Mapu Barber nació de la pasión por el oficio y la convicción de que una barbería puede ser mucho más que un espacio de corte. Hoy, con dos sucursales en la región, somos un referente de la barbería clásica en Chile.<br><br>Cada barbero que forma parte de nuestro equipo comparte los mismos valores: precisión, respeto por el cliente y amor por el oficio. A través de la Academia Mapu Barber, hemos egresado más de 24 generaciones de barberos que hoy ejercen su profesión con orgullo en todo Chile.',
      logo:            '/mapu2.png',
      logo2:           '/mapu2.png',
      direccion:       '',
      horario:         '',
      telefono:        '',
      club:            'Club Mapu',
      instagram:       '',
      instagramHandle: '',
      waEmoji:         '✂️',
      googleReviewUrl: 'https://g.page/r/CSAV1u-lXwVeEBM/review',
      ratingGeneral: 4.8,
      totalReviews:  72,
      reviews: [
        { author: 'Tomás E.',   rating: 5, text: 'Dos sucursales y en ambas el nivel es excelente. Mi favorito en Valparaíso y Viña del Mar.' },
        { author: 'Ignacio F.', rating: 5, text: 'El corte perfecto y el ambiente de barbería que te hace volver. Siempre satisfecho.' },
        { author: 'Andrés C.',  rating: 5, text: 'Profesionalismo total. Me dejaron exactamente el estilo que quería. Barbaros todos.' },
      ],
      sucursales: [
        {
          id:        'valparaiso',
          nombre:    'Mapu Barber Shop Valparaíso',
          calle:     'Blanco 974 Local 01',
          ciudad:    'Valparaíso',
          mapsUrl:   'https://maps.google.com/?q=Blanco+974+Local+01+Valparaíso+Chile',
        },
        {
          id:        'vinadelmar',
          nombre:    'Mapu Barber Shop Viña del Mar',
          calle:     '1 Oriente 876 Casi esq. 10 Norte',
          ciudad:    'Viña del Mar',
          mapsUrl:   'https://maps.google.com/?q=1+Oriente+876+Viña+del+Mar+Chile',
        },
      ],
      barberos: [
        // ── Ambas sucursales ────────────────────────────────────────
        { id: 'luka-araya',          nombre: 'Luka Araya',          foto: null, disponible: true },
        { id: 'ivi-soto',            nombre: 'Ivi Soto',            foto: null, disponible: true },
        { id: 'felipe-vergara',      nombre: 'Felipe Vergara',      foto: null, disponible: true },
        { id: 'lucia-fuentes',       nombre: 'Lucia Fuentes',       foto: null, disponible: true },
        { id: 'santiago-echeverria', nombre: 'Santiago Echeverria', foto: null, disponible: true },
        { id: 'jonathan-chamorro',   nombre: 'Jonathan Chamorro',   foto: null, disponible: true },
        // ── Solo Valparaíso ─────────────────────────────────────────
        { id: 'fernanda-soudre',     nombre: 'Fernanda Soudre',     foto: null, disponible: true, sucursalId: 'valparaiso'  },
        // ── Solo Viña del Mar ───────────────────────────────────────
        { id: 'renato-perez',        nombre: 'Renato Perez',        foto: null, disponible: true, sucursalId: 'vinadelmar'  },
        { id: 'daniela-ramirez',     nombre: 'Daniela Ramirez',     foto: null, disponible: true, sucursalId: 'vinadelmar'  },
        { id: 'ian-alcalde',         nombre: 'Ian Alcalde',         foto: null, disponible: true, sucursalId: 'vinadelmar'  },
        { id: 'gabriel-apablaza',    nombre: 'Gabriel Apablaza',    foto: null, disponible: true, sucursalId: 'vinadelmar'  },
      ],
    },
    aura: {
      categoriasServicio: ['Cortes de Cabello', 'Barba', 'Packs', 'Tratamientos', 'Suscripciones Mensuales', 'Experiencias Premium'],
      nombre:          'AURA SALÓN & MALE GROOMING',
      nombreCorto:     'AURA',
      pageTitle:       'AURA SALÓN | Agenda tu hora',
      slogan:          'Eleva Tu Aura',
      sobreNosotros:   '✨ AURA SALÓN & MALE GROOMING ✂️<br><br>Más que una barbería, somos un espacio creado para el cuidado, el estilo y la experiencia masculina moderna. En AURA combinamos técnica, diseño y detalles para ofrecerte un servicio integral: cortes clásicos y contemporáneos, perfilado de barba, tratamientos capilares y una atención pensada para tu bienestar.<br><br>Cada visita es una pausa en la rutina, un momento para verte y sentirte mejor.<br><br>💈 Estilo, precisión y personalidad — eso es AURA.',
      logo:            '/aura.png',
      direccion:       '',
      horario:         '',
      telefono:        '',
      club:            'Club AURA',
      instagram:       '',
      instagramHandle: '',
      waEmoji:         '✂️',
      googleReviewUrl: 'https://g.page/r/CRw9h990wQ5jEBM/review',
      ratingGeneral: 5.0,
      totalReviews:  43,
      reviews: [
        { author: 'Rafael Contador',    rating: 5, text: 'Tremenda experiencia! Fui por un corte de pelo y a arreglarme la barba y quedé más que satisfecho. Chiky Barber me entendió perfectamente lo que quería y fue muy detallista. El ambiente es muy agradable y el servicio impecable. Definitivamente volveré y lo recomiendo al 100%.' },
        { author: 'Luciano Bravo',      rating: 5, text: 'Excelente experiencia y maravilloso servicio, pasar el rato con un cafecito y cortarse el pelo deja un Aura semanal 🔥' },
        { author: 'Ignacio Ibaceta',    rating: 5, text: 'Súper buena atención! Servicio completo y perfecto para ir a relajarse, hasta un café ofrecieron al momento de atenderme!' },
      ],
      barberos: [],
    },
    machos: {
      categoriasServicio: ['Cortes', 'Barba', 'Combos', 'Extras', 'Otros'],
      nombre:          "Macho´s Barbershop",
      nombreCorto:     "Macho's",
      pageTitle:       "Macho´s Barbershop | Calidad y Asesoría Profesional",
      slogan:          'En Barbería Machos ofrecemos servicios de calidad y contamos con profesionales de primer nivel.',
      logo:            '/machos.png',
      direccion:       '📍 4 Norte 477 local 5 | Viña del Mar',
      horario:         '🕒 Lun a Sáb: 10:00 – 20:00 hrs | Dom y Feriados: 11:00 – 17:00 hrs',
      telefono:        '56978390422',
      club:            'Club Machos',
      instagram:       'https://www.instagram.com/machos_barbershop.cl/',
      instagramHandle: '@machos_barbershop.cl',
      waEmoji:         '💈',
      googleReviewUrl: '',
      ratingGeneral: 4.9,
      totalReviews:  32,
      reviews: [
        { author: 'Cristian E.', rating: 5, text: 'Excelente atención de los muchachos, profesionalismo en cada corte.' },
        { author: 'Matías O.', rating: 5, text: 'Buen ambiente, limpio, acogedor y el corte impecable. Recomiendo totalmente.' },
        { author: 'Gonzalo F.', rating: 5, text: 'Un agrado atenderse aquí. Muy cuidadosos con el rebaje de barba y toallas calientes.' },
      ],
      barberos: [
        { nombre: 'Álvaro Muñoz', foto: null, disponible: true },
        { nombre: 'Carlos Rivas', foto: null, disponible: true },
        { nombre: 'Sebastián Jara', foto: null, disponible: true },
      ],
    },
    infinity: {
      categoriasServicio: ['Cortes', 'Barba', 'Combos', 'Color', 'Facial', 'Extras'],
      nombre:          'INFINITY STUDIO',
      nombreCorto:     'Infinity',
      pageTitle:       'INFINITY STUDIO | Estilo y Confianza en Viña del Mar',
      slogan:          'Ambiente familiar y confianza son nuestra esencia. Resultados de alto nivel.',
      logo:            '/infinity.png',
      direccion:       '📍 Traslaviña 114 | Viña del Mar',
      horario:         '🕒 Lun a Sáb: 10:00 – 20:00 hrs.',
      telefono:        '56985551234',
      club:            'Club Infinity',
      instagram:       'https://www.instagram.com/infinitystudio23/',
      instagramHandle: '@infinitystudio23',
      waEmoji:         '💈',
      googleReviewUrl: '',
      ratingGeneral: 5.0,
      totalReviews:  12,
      reviews: [
        { author: 'Claudio Valdivia', rating: 5, text: 'Excelente atención, el ambiente es súper agradable y familiar. Los cabros cortan con un nivel técnico altísimo. Totalmente recomendado!' },
        { author: 'Rodrigo Espinoza', rating: 5, text: 'Llevo meses cortándome acá y el servicio es siempre de primer nivel. Un agrado de barbería en Viña.' },
      ],
      barberos: [
        { nombre: 'Miguel Martínez', foto: null, disponible: true },
        { nombre: 'Elio Alfonso', foto: null, disponible: true },
        { nombre: 'Jose Luis Cordero', foto: null, disponible: true },
        { nombre: 'Mailo Serrano', foto: null, disponible: true },
      ],
    },
    sionbarberia: {
      categoriasServicio: ['Cortes', 'Barba', 'Combos', 'Color', 'Facial', 'Extras'],
      nombre:          'Sion Barbería',
      nombreCorto:     'Sion',
      pageTitle:       'Sion Barbería | Calidad y Profesionalismo en Viña del Mar',
      slogan:          'Una barbería destacada para brindar un servicio de primera calidad brindándote asesoría de imagen y profesionalismo.',
      logo:            '/sion.png',
      direccion:       '📍 Av. Libertad 123, Viña del Mar',
      horario:         '🕒 Lunes a sábado 10:00-20:00',
      telefono:        '56988888888',
      club:            'Club Sion',
      instagram:       'https://www.instagram.com/sionbarberia/',
      instagramHandle: '@sionbarberia',
      waEmoji:         '💈',
      googleReviewUrl: '',
      ratingGeneral: 4.9,
      totalReviews:  18,
      reviews: [
        { author: 'Carlos Gutiérrez', rating: 5, text: 'Excelente atención y asesoría de imagen. El corte premium es fantástico.' },
        { author: 'Andrés Vera', rating: 5, text: 'Un local limpio, moderno y los barberos son de primer nivel. Recomendado.' },
      ],
      barberos: [
        { nombre: 'Nelson Barber', foto: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop', disponible: true },
        { nombre: 'Ignacio Barber', foto: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&h=150&fit=crop', disponible: true },
        { nombre: 'Marcelo Barber', foto: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop', disponible: true },
      ],
    },
  };

  // Resolver tenant: query param > dominio > sessionStorage > default
  let tenantId = '';
  try {
    tenantId = new URL(window.location.href).searchParams.get('local') || '';
  } catch (_) {}

  // Si llega por URL, persistir en sessionStorage para esta pestaña
  if (tenantId && _tenants[tenantId]) {
    try { sessionStorage.setItem('saas_current_tenant', tenantId); } catch (_) {}
  }

  // Fallback: dominio configurado
  if (!tenantId || !_tenants[tenantId]) {
    tenantId = _domainMap[window.location.hostname.toLowerCase()] || '';
  }

  // Fallback: sessionStorage (navegar entre páginas del panel sin perder el tenant)
  if (!tenantId || !_tenants[tenantId]) {
    try { tenantId = sessionStorage.getItem('saas_current_tenant') || ''; } catch (_) {}
  }

  if (!_tenants[tenantId]) tenantId = 'elegance';

  window.CURRENT_TENANT_ID = tenantId;
  window.SHOP = _tenants[tenantId];
  document.documentElement.classList.add('tenant-' + tenantId);

  var _logoSrc = _tenants[tenantId] && _tenants[tenantId].logo;
  if (_logoSrc) {
    var _favicon = document.querySelector('link[rel="icon"]');
    if (_favicon) _favicon.href = _logoSrc;
    var _touchIcon = document.querySelector('link[rel="apple-touch-icon"]');
    if (_touchIcon) _touchIcon.href = _logoSrc;
  }
})();
